//Post action
const LOADING = "EN CHARGE";
const ALL_POST = "TOUS LES POSTS";
const ALL_INFO = "TOUTES LES INFO";
const ALL_PROBLEME = "TOUTES LES PROBLEMES";
const ALL_SOUVENIR = "TOUTES LES SOUVENIRS";
const ERROR = "ERROR";

//User action
const CONNEXION = "CONNEXION";
const DECONNEXION = "DECONNEXION";
const RELOADING = "RELOADING";
const USER = "USER";
const USERS = "USERS";

export {
  LOADING,
  ALL_POST,
  ERROR,
  CONNEXION,
  DECONNEXION,
  RELOADING,
  USER,
  USERS,
  ALL_INFO,
  ALL_PROBLEME,
  ALL_SOUVENIR,
};
